[package]
name = "rabia-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_usage"
path = "basic_usage.rs"

[[bin]]
name = "kvstore_usage"
path = "kvstore_usage.rs"

[[bin]]
name = "consensus_cluster"
path = "consensus_cluster.rs"

[[bin]]
name = "performance_benchmark"
path = "performance_benchmark.rs"

[dependencies]
rabia-core = { path = "../rabia-core" }
rabia-engine = { path = "../rabia-engine" }
rabia-network = { path = "../rabia-network" }
rabia-persistence = { path = "../rabia-persistence" }
rabia-kvstore = { path = "../rabia-kvstore" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }