name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --all-features

    - name: Run unit tests
      run: |
        echo "CI=true" >> $GITHUB_ENV
        cargo test --all-features

    - name: Run integration tests
      run: |
        echo "CI=true" >> $GITHUB_ENV
        cargo test --test '*' --all-features

    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit