name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: |
        echo "CI=true" >> $GITHUB_ENV
        cargo test --all-features

    - name: Build packages
      run: cargo build --release --all-features

    - name: Publish to crates.io
      run: |
        cargo install cargo-workspaces
        cargo ws publish --all --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --from-git --yes

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Rabia v${{ steps.version.outputs.version }}
        body: |
          # Rabia v${{ steps.version.outputs.version }}

          ## Installation
          ```bash
          cargo add rabia-core@${{ steps.version.outputs.version }}
          ```

          ## Documentation
          - [API Documentation](https://docs.rs/rabia-core/${{ steps.version.outputs.version }})
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}