name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: |
        echo "CI=true" >> $GITHUB_ENV
        cargo test --all-features

    - name: Build packages
      run: cargo build --release --all-features

    - name: Publish to crates.io
      run: |
        set -e
        
        # Function to publish with retry
        publish_crate() {
          local crate=$1
          local max_retries=3
          local delay=10
          
          for i in $(seq 1 $max_retries); do
            echo "Publishing $crate (attempt $i/$max_retries)..."
            if cargo publish -p "$crate" --token ${{ secrets.CARGO_REGISTRY_TOKEN }}; then
              echo "✅ Successfully published $crate"
              return 0
            else
              if [ $i -eq $max_retries ]; then
                echo "❌ Failed to publish $crate after $max_retries attempts"
                return 1
              fi
              echo "⚠️  Failed to publish $crate, retrying in ${delay}s..."
              sleep $delay
            fi
          done
        }
        
        # Publish in dependency order
        echo "=== Publishing core crates ==="
        
        publish_crate "rabia-core"
        
        echo "Waiting for rabia-core to be indexed on crates.io..."
        sleep 60
        
        publish_crate "rabia-persistence"
        
        echo "Waiting for rabia-persistence to be indexed..."
        sleep 30
        
        publish_crate "rabia-engine"
        
        echo "Waiting for rabia-engine to be indexed..."
        sleep 30
        
        publish_crate "rabia-kvstore"
        
        echo "=== Publishing example crates ==="
        
        echo "Waiting for dependencies to be indexed..."
        sleep 30
        
        publish_crate "counter-smr"
        publish_crate "banking-smr" 
        publish_crate "kvstore-smr"
        
        echo "🎉 All crates published successfully!"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Rabia v${{ steps.version.outputs.version }}
        body: |
          # Rabia v${{ steps.version.outputs.version }}

          ## Installation
          ```bash
          cargo add rabia-core@${{ steps.version.outputs.version }}
          ```

          ## Documentation
          - [API Documentation](https://docs.rs/rabia-core/${{ steps.version.outputs.version }})
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}